### ISSUE TITLE
Download link in spring-eg-content-fs returns 404 when using Firefox 

### ISSUE THREAD

**Issue by nategrover** [paulcwarren/spring-content-examples#1]
In the spring-eg-content-fs project, the download link doesn't work when using latest version of Firefox on Windows 8.  The specific firefox version I'm using is 55.0.3 (32-bit).

**Comment by paulcwarren** [comment]
[Fixed](https://github.com/paulcwarren/spring-content-gettingstarted/commit/6107e26f30f8a2f08344df5c8c1633a078f76356).

Let me know if you have any further issues.
