### ISSUE TITLE
S3 readme has wrong environment variable names

### ISSUE THREAD

**Issue by nategrover** [paulcwarren/spring-content-examples#2]
In the Readme for the spring-eg-content-s3-boot-starter it has some environment variables to use to configure your S3 connection.   They are listed as

AWS_S3_BUCKET 
AWS_S3_REGION

but after that didn't work and digging through the code, it appears the they should be 

AWS_BUCKET 
AWS_REGION

**Comment by paulcwarren** [comment]
Fixed.  Thx @nategrover
